### ISSUE TITLE
Missing time slots / spans

### ISSUE THREAD

**Issue by ske14002** [DSD-BookEasy/BookEasy#28]
Time slots / time spans are not shown while requesting a booking. Calendar remains empty. Not sure if we should remove it anyway.

**Comment by robertengelmann** [comment]
Hm. Not sure about that. It doesn't hurt, does it? Well, it wouldn't hurt if it was actually filled with information.

**Comment by ste-camp** [comment]
It *was* working.
The purpose of the booking weekdays page is to enable people to request things out of the existing timeslots. NOBODY would care of seeing the existing timeslots there, because they want to make new ones.
The calendar was indeed showing the timeslots, they were just set as background objects affecting the calendar background color only to tell people where they could not make their request.

**Comment by robertengelmann** [comment]
oh! I was not realizing that. Indeed. So are we using it or not? What do you guys think?

**Comment by BaggioAlessandro** [comment]
It is quite useful in my opinion and it is actually working. So let's keep it
