### ISSUE TITLE
Change $ to kr

### ISSUE THREAD

**Issue by robertengelmann** [DSD-BookEasy/BookEasy#35]
We have to change the currency to kroner.

**Comment by ste-camp** [comment]
If we plan to use the system only in swedish language, then it is as easy an enabling Swedish language and all $ symbols will get changed into kr automatically (for the places where we use the App::t() method)

Otherwise, if both languages are needed, we need to actually insert the kr in the sentences and avoi using the currency formatter

**Comment by robertengelmann** [comment]
I think the problem is, that you will have to pay 200kr (!= 200$) regardless of which language you speak :P
So we should make that fix. Well Wikipedia says the short form (equivalent to $/€) is Skr (swedish krona, pl. kronor). So we could just have a string and give up on the automatic currency conversion.

**Comment by ske14002** [comment]
Everything should be in SEK regardless of the language in use to my mind. Let us ask Thijmen which abbreviation he prefers.
